// <auto-generated />
using CapenexisStudents2023.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapenexisStudents2023.Migrations
{
    [DbContext(typeof(CapenexisStudents2023Context))]
    [Migration("20230228082633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapenexisStudents2023.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacilitataorId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("CapenexisStudents2023.Models.Facilitator", b =>
                {
                    b.Property<int>("FacilitatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilitatorId"));

                    b.Property<string>("FacilitatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilitatorSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilitatorId");

                    b.ToTable("Facilitator");
                });

            modelBuilder.Entity("CapenexisStudents2023.Models.Learner", b =>
                {
                    b.Property<long>("LearnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LearnerId"));

                    b.Property<string>("LearnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearnerSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LearneridentityNumber")
                        .HasColumnType("bigint");

                    b.HasKey("LearnerId");

                    b.ToTable("Learner");
                });
#pragma warning restore 612, 618
        }
    }
}
